{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @pytest.mark.basic_sanity\n    def test_failure():\n        allure.dynamic.suite(\"SUITE_1\")\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:47: AssertionError"}, "attachments": [{"name": "stdout", "source": "00d264b1-3544-42d2-b3c2-e5c2b4cb5334-attachment.txt", "type": "text/plain"}], "start": 1694122730322, "stop": 1694122730322, "uuid": "89a01f83-a3b9-4da9-bea3-960829f8c132", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "suite", "value": "SUITE_1"}, {"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "tag", "value": "basic_sanity"}, {"name": "host", "value": "fv-az417-817"}, {"name": "thread", "value": "2123-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}