{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @pytest.mark.basic_sanity\n    def test_failure():\n        allure.dynamic.suite(\"SUITE_1\")\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:47: AssertionError"}, "attachments": [{"name": "stdout", "source": "14c47cff-03ac-40ad-8109-ec12f9c1534b-attachment.txt", "type": "text/plain"}], "start": 1693210554614, "stop": 1693210554615, "uuid": "28db11c3-9ce0-40bb-a2f1-34fd16df54a1", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "suite", "value": "SUITE_1"}, {"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "tag", "value": "basic_sanity"}, {"name": "host", "value": "fv-az621-295"}, {"name": "thread", "value": "2201-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}