{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @pytest.mark.basic_sanity\n    def test_failure():\n        allure.dynamic.suite(\"SUITE_1\")\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:47: AssertionError"}, "attachments": [{"name": "stdout", "source": "cd7541c6-3c64-4bf2-8204-f4c826e8b4b6-attachment.txt", "type": "text/plain"}], "start": 1693333182268, "stop": 1693333182268, "uuid": "112f7ae6-aba5-43d4-a3d3-7c21527d914d", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "suite", "value": "SUITE_1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "tag", "value": "basic_sanity"}, {"name": "host", "value": "fv-az590-8"}, {"name": "thread", "value": "2035-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}