{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @pytest.mark.basic_sanity\n    def test_failure():\n        allure.dynamic.suite(\"SUITE_1\")\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:47: AssertionError"}, "attachments": [{"name": "stdout", "source": "e7d117a3-d18e-4e0e-a022-0cc573662947-attachment.txt", "type": "text/plain"}], "start": 1694008665886, "stop": 1694008665886, "uuid": "0ecabdda-26d3-437d-83f4-4b9856b69614", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "suite", "value": "SUITE_1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "tag", "value": "basic_sanity"}, {"name": "host", "value": "fv-az589-776"}, {"name": "thread", "value": "2092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}