{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @pytest.mark.basic_sanity\n    def test_failure():\n        allure.dynamic.suite(\"SUITE_1\")\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:47: AssertionError"}, "attachments": [{"name": "stdout", "source": "4d5c1767-57bc-4b1c-91ba-4932f1fb1fe4-attachment.txt", "type": "text/plain"}], "start": 1694213640817, "stop": 1694213640817, "uuid": "4bb2ef19-571a-451f-853f-54209eaeff12", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "suite", "value": "SUITE_1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "tag", "value": "basic_sanity"}, {"name": "host", "value": "fv-az485-497"}, {"name": "thread", "value": "2117-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}