{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @pytest.mark.basic_sanity\n    def test_failure():\n        allure.dynamic.suite(\"SUITE_1\")\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:47: AssertionError"}, "attachments": [{"name": "stdout", "source": "dd94e949-e813-4f6c-b998-1e0c64e6369d-attachment.txt", "type": "text/plain"}], "start": 1693972822937, "stop": 1693972822937, "uuid": "53bfdb9b-5f47-4731-b011-5d92260e8219", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "suite", "value": "SUITE_1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "tag", "value": "basic_sanity"}, {"name": "host", "value": "fv-az336-847"}, {"name": "thread", "value": "2089-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}