{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @pytest.mark.basic_sanity\n    def test_failure():\n        allure.dynamic.suite(\"SUITE_1\")\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:47: AssertionError"}, "attachments": [{"name": "stdout", "source": "4e9094af-7d4b-4855-be85-d34d2854d720-attachment.txt", "type": "text/plain"}], "start": 1694014953518, "stop": 1694014953519, "uuid": "75af93e7-9880-40af-b770-7c446a99e9cd", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "suite", "value": "SUITE_1"}, {"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "tag", "value": "basic_sanity"}, {"name": "host", "value": "fv-az592-733"}, {"name": "thread", "value": "2066-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}